/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_jvmti_utils_ClassUtils */

#ifndef _Included_com_jvmti_utils_ClassUtils
#define _Included_com_jvmti_utils_ClassUtils
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_jvmti_utils_ClassUtils
	 * Method:    initialize
	 * Signature: (Ljava/lang/ClassLoader;Lcom/jvmti/utils/ClassUtils;)V
	 */
	JNIEXPORT void JNICALL Java_com_jvmti_utils_ClassUtils_initialize
	(JNIEnv*, jclass, jobject, jobject);

	/*
	 * Class:     com_jvmti_utils_ClassUtils
	 * Method:    redefineClass
	 * Signature: (Ljava/lang/Class;[B)V
	 */
	JNIEXPORT void JNICALL Java_com_jvmti_utils_ClassUtils_redefineClass
	(JNIEnv*, jclass, jclass, jbyteArray);

	/*
	 * Class:     com_jvmti_utils_ClassUtils
	 * Method:    retransformClass
	 * Signature: (Ljava/lang/Class;)V
	 */
	JNIEXPORT void JNICALL Java_com_jvmti_utils_ClassUtils_retransformClass
	(JNIEnv*, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
